language: go

sudo: false

go:
  - 1.5
  - tip

env:
  - GOARCH=amd64

install:
  - export PATH="$HOME/gopath/bin:$PATH"
  - go get github.com/tools/godep
  - go get -t -d ./...
  - godep restore ./...

script:
  - cd $HOME/gopath/src/github.com/backstage/beat
  - go test -x ./...

notifications:
  email:
    recipients:
      - backstage1@corp.globo.com
      - backstage2@corp.globo.com

